ExpProcesosList:
    pattern:  /procesos
    defaults: { _controller: ExpidianProcesosBundle:Procesos:index}

ExpAjaxProcesosList:
    pattern:  /procesos/ajax/lista/{page}
    defaults: { _controller: ExpidianProcesosBundle:Procesos:ajaxListaProcesos, page: 1}
  
ExpProcesosNew:
    pattern:  /procesos/nuevo
    defaults: { _controller: ExpidianProcesosBundle:Procesos:new}
    
ExpProcesosEdit:
    pattern:  /procesos/edit/{id_proceso}
    defaults: { _controller: ExpidianProcesosBundle:Procesos:edit}
    
ExpProcesosDelete:
    pattern:  /procesos/eliminar/{id_proceso}
    defaults: { _controller: ExpidianProcesosBundle:Procesos:delete}
